#!/usr/bin/env node
/**
 * MarkFlow — Intelligent Markdown Editor
 * Part of the Adaptive Intelligence Platform
 * License: MIT
 * 
 * Automatically generates documentation from:
 * - SCP capsules
 * - Compliance reports
 * - Strategy validation results
 * - System status
 */

const fs = require('fs');
const path = require('path');

class MarkFlow {
  constructor() {
    this.docsDir = path.join(process.env.HOME, 'kraken-intelligence', 'docs');
    if (!fs.existsSync(this.docsDir)) {
      fs.mkdirSync(this.docsDir, { recursive: true });
    }
  }

  // Generate README from SCP capsule
  generateStrategyReadme(capsulePath, outputPath = null) {
    const capsuleFile = path.join(capsulePath, 'capsule.json');
    if (!fs.existsSync(capsuleFile)) {
      return { error: 'Capsule not found' };
    }
    
    const capsule = JSON.parse(fs.readFileSync(capsuleFile, 'utf8'));
    const manifest = capsule.manifest;
    const strategy = capsule.semantic_context || capsule.strategy || {};
    const watermark = capsule.watermark || {};
    
    let readme = `# 🧠 ${manifest.name}\n\n`;
    readme += `## Strategy Overview\n\n`;
    readme += `| Property | Value |\n`;
    readme += `|----------|-------|\n`;
    readme += `| ID | ${manifest.id} |\n`;
    readme += `| Type | ${manifest.type} |\n`;
    readme += `| Version | ${manifest.version} |\n`;
    readme += `| Status | ${manifest.status} |\n`;
    readme += `| Exchange | ${manifest.exchange} |\n`;
    readme += `| Symbol | ${manifest.symbol} |\n`;
    readme += `| Timeframe | ${manifest.timeframe} |\n`;
    readme += `| Capital | $${manifest.capital} |\n\n`;
    
    readme += `## Parameters\n\n`;
    readme += `| Parameter | Value |\n`;
    readme += `|-----------|-------|\n`;
    if (manifest.parameters) {
      for (const [key, value] of Object.entries(manifest.parameters)) {
        readme += `| ${key} | ${value} |\n`;
      }
    }
    readme += `\n`;
    
    readme += `## Entry Rules\n\n`;
    const entryRules = strategy.entry_rules || strategy.entryRules || [];
    readme += `\`\`\`json\n${JSON.stringify(entryRules, null, 2)}\n\`\`\`\n\n`;
    
    readme += `## Exit Rules\n\n`;
    const exitRules = strategy.exit_rules || strategy.exitRules || [];
    readme += `\`\`\`json\n${JSON.stringify(exitRules, null, 2)}\n\`\`\`\n\n`;
    
    if (watermark.fingerprint) {
      readme += `## Watermark\n\n`;
      readme += `| Property | Value |\n`;
      readme += `|----------|-------|\n`;
      readme += `| Fingerprint | \`${watermark.fingerprint}\` |\n`;
      readme += `| Generated | ${watermark.timestamp} |\n`;
      readme += `| Hash | \`${watermark.hash.substring(0, 16)}...\` |\n\n`;
    }
    
    readme += `## Validation Status\n\n`;
    if (capsule.validation) {
      readme += `| Metric | Value |\n`;
      readme += `|--------|-------|\n`;
      readme += `| Passed | ${capsule.validation.passed ? '✅' : '❌'} |\n`;
      readme += `| Score | ${capsule.validation.score || 'N/A'} |\n`;
      readme += `| Grade | ${capsule.validation.grade || 'N/A'} |\n`;
    } else {
      readme += `*Not yet validated*\n\n`;
    }
    
    readme += `---\n`;
    readme += `*Generated by MarkFlow on ${new Date().toISOString()}*\n`;
    readme += `*Part of the Adaptive Intelligence Platform*\n`;
    
    const output = outputPath || path.join(this.docsDir, `${manifest.id}_README.md`);
    fs.writeFileSync(output, readme);
    
    return { success: true, path: output, readme };
  }

  // Generate compliance report in markdown
  generateComplianceReport(compliancePath = null) {
    const complianceDir = path.join(process.env.HOME, 'kraken-intelligence', 'compliance');
    const locksFile = path.join(complianceDir, 'locks.json');
    const strategiesFile = path.join(complianceDir, 'strategies.json');
    
    if (!fs.existsSync(locksFile)) {
      return { error: 'Compliance data not found' };
    }
    
    const locks = JSON.parse(fs.readFileSync(locksFile, 'utf8'));
    const strategies = fs.existsSync(strategiesFile) ? 
      JSON.parse(fs.readFileSync(strategiesFile, 'utf8')) : [];
    
    let report = `# 🛡️ Aegis Compliance Report\n\n`;
    report += `## Three Locks Status\n\n`;
    report += `| Lock | Requirement | Status |\n`;
    report += `|------|-------------|--------|\n`;
    report += `| Lock 1 | 30-Day Dry Run | ${locks.lock1_dry_run_days}/30 days ${locks.lock1_complete ? '✅' : '⏳'} |\n`;
    report += `| Lock 2 | Strategy Validation | ${locks.lock2_validation_passed ? '✅ PASSED' : '⏳ PENDING'} |\n`;
    report += `| Lock 3 | API Key Present | ${locks.lock3_api_key_present ? '✅ PRESENT' : '⏳ MISSING'} |\n\n`;
    
    report += `## Overall Status\n\n`;
    report += `**${locks.overall_status}**\n\n`;
    
    if (strategies.length > 0) {
      report += `## Recent Validations\n\n`;
      report += `| Date | Strategy | Grade | Result |\n`;
      report += `|------|----------|-------|--------|\n`;
      const recent = strategies.slice(-5);
      for (const s of recent) {
        report += `| ${s.timestamp.split('T')[0]} | ${s.strategyId} | ${s.grade || 'N/A'} | ${s.passed ? '✅' : '❌'} |\n`;
      }
      report += `\n`;
    }
    
    report += `---\n`;
    report += `*Generated by MarkFlow on ${new Date().toISOString()}*\n`;
    
    const output = path.join(this.docsDir, `compliance_report_${new Date().toISOString().split('T')[0]}.md`);
    fs.writeFileSync(output, report);
    
    return { success: true, path: output, report };
  }

  // Generate system status dashboard
  generateStatusDashboard() {
    let dashboard = `# 🔮 S.O.T.O.S MK1 — System Dashboard\n\n`;
    dashboard += `## System Overview\n\n`;
    dashboard += `| Component | Status |\n`;
    dashboard += `|-----------|--------|\n`;
    
    // Check each component
    const components = [
      { name: 'Data Collector', path: '~/kraken-intelligence/collect.js' },
      { name: 'Analysis Engine', path: '~/kraken-intelligence/analyse.js' },
      { name: 'Forge Reasoning', path: '~/kraken-intelligence/forge-reasoning.js' },
      { name: 'Forge Validator', path: '~/kraken-intelligence/forge-validator.js' },
      { name: 'Forge Auto Loop', path: '~/kraken-intelligence/forge_auto.js' },
      { name: 'Forge Monitor', path: '~/kraken-intelligence/forge-monitor.js' },
      { name: 'Forge Dashboard', path: '~/kraken-intelligence/forge-dashboard.js' },
      { name: 'Evolution Engine', path: '~/kraken-intelligence/forge-evolution.js' },
      { name: 'Regime Watcher', path: '~/kraken-intelligence/regime_watcher.js' },
      { name: 'SCP Updater', path: '~/kraken-intelligence/scp-auto-updater.js' },
      { name: 'ChronoScribe', path: '~/kraken-intelligence/chronoscribe.js' },
      { name: 'Whisper', path: '~/kraken-intelligence/tools/whisper/index.js' },
      { name: 'Aegis', path: '~/kraken-intelligence/tools/aegis/index.js' },
      { name: 'EmbedID', path: '~/kraken-intelligence/tools/embedid/index.js' },
      { name: 'MarkFlow', path: '~/kraken-intelligence/tools/markflow/index.js' }
    ];
    
    for (const comp of components) {
      const exists = fs.existsSync(comp.path.replace('~', process.env.HOME));
      dashboard += `| ${comp.name} | ${exists ? '✅' : '❌'} |\n`;
    }
    
    dashboard += `\n## SCP Capsules\n\n`;
    const scpDir = path.join(process.env.HOME, 'cce', 'engines', 'scp');
    if (fs.existsSync(scpDir)) {
      const capsules = fs.readdirSync(scpDir);
      for (const capsule of capsules) {
        dashboard += `- \`${capsule}\`\n`;
      }
    } else {
      dashboard += `*No capsules found*\n`;
    }
    
    dashboard += `\n---\n`;
    dashboard += `*Dashboard generated by MarkFlow on ${new Date().toISOString()}*\n`;
    dashboard += `*Part of the Adaptive Intelligence Platform*\n`;
    
    const output = path.join(this.docsDir, `dashboard_${new Date().toISOString().split('T')[0]}.md`);
    fs.writeFileSync(output, dashboard);
    
    return { success: true, path: output, dashboard };
  }
}

module.exports = MarkFlow;
