#!/bin/bash

# Generate 30-day evaluation report
# Run manually or after 30 days of data collection

REPORT_DIR="$HOME/kraken-intelligence/reports"
DAILY_DIR="$REPORT_DIR/daily"
OUTPUT_FILE="$REPORT_DIR/30day_evaluation_$(date +%Y%m%d).md"

echo "📊 Generating 30-day evaluation report..."

# Collect all daily reports from last 30 days
REPORTS=$(find "$DAILY_DIR" -name "*_report.json" -type f -mtime -30 2>/dev/null | sort)

if [ -z "$REPORTS" ]; then
    echo "❌ No daily reports found. Run daily_capture.sh first for at least one day."
    exit 1
fi

# Calculate metrics
TOTAL_DAYS=$(echo "$REPORTS" | wc -l)
FIRST_REPORT=$(echo "$REPORTS" | head -1)
LAST_REPORT=$(echo "$REPORTS" | tail -1)

START_CAPITAL=$(jq -r '.capital' "$FIRST_REPORT" 2>/dev/null)
END_CAPITAL=$(jq -r '.capital' "$LAST_REPORT" 2>/dev/null)
TOTAL_TRADES=$(jq -r '.trades' "$LAST_REPORT" 2>/dev/null)

# Calculate win rate from engine state
ENGINE_STATE="$HOME/kraken-intelligence/dryrun/engine_state.json"
if [ -f "$ENGINE_STATE" ]; then
    WINS=$(jq -r '[.trades[] | select(.win==true)] | length' "$ENGINE_STATE" 2>/dev/null)
    LOSSES=$(jq -r '[.trades[] | select(.win==false)] | length' "$ENGINE_STATE" 2>/dev/null)
    if [ $((WINS + LOSSES)) -gt 0 ]; then
        WIN_RATE=$(echo "scale=1; $WINS * 100 / ($WINS + $LOSSES)" | bc -l 2>/dev/null)
    else
        WIN_RATE=0
    fi
else
    WINS=0
    LOSSES=0
    WIN_RATE=0
fi

# Calculate total return
TOTAL_RETURN=$(echo "scale=2; ($END_CAPITAL - $START_CAPITAL) / $START_CAPITAL * 100" | bc -l 2>/dev/null)

# Calculate max drawdown
MAX_DRAWDOWN=0
PEAK=$START_CAPITAL
for report in $REPORTS; do
    CAP=$(jq -r '.capital' "$report" 2>/dev/null)
    if (( $(echo "$CAP > $PEAK" | bc -l) )); then
        PEAK=$CAP
    fi
    DD=$(echo "scale=2; ($PEAK - $CAP) / $PEAK * 100" | bc -l 2>/dev/null)
    if (( $(echo "$DD > $MAX_DRAWDOWN" | bc -l) )); then
        MAX_DRAWDOWN=$DD
    fi
done

# Calculate daily returns
AVG_DAILY_RETURN=$(jq -r '.daily_return // 0' $DAILY_DIR/*_report.json 2>/dev/null | awk '{sum+=$1; count++} END {if(count>0) print sum/count; else print 0}')

# Count signal days
SIGNAL_DAYS=$(jq -r 'select(.signal_active==true) | .date' $DAILY_DIR/*_report.json 2>/dev/null | wc -l)

# Generate report
cat > "$OUTPUT_FILE" << MD
# Four Red Days — 30-Day Evaluation Report
**Generated:** $(date '+%Y-%m-%d %H:%M:%S')
**Period:** $(basename "$FIRST_REPORT" | cut -d'_' -f1) to $(basename "$LAST_REPORT" | cut -d'_' -f1)
**Days:** $TOTAL_DAYS

---

## 📊 Performance Summary

| Metric | Value |
|--------|-------|
| Starting Capital | \$$START_CAPITAL |
| Ending Capital | \$$END_CAPITAL |
| **Total Return** | **${TOTAL_RETURN}%** |
| Total Trades | $TOTAL_TRADES |
| Wins | $WINS |
| Losses | $LOSSES |
| **Win Rate** | **${WIN_RATE}%** |
| Avg Daily Return | ${AVG_DAILY_RETURN}% |
| Max Drawdown | ${MAX_DRAWDOWN}% |
| Signal Days (4+ red) | $SIGNAL_DAYS |

---

## 📈 Comparison to Backtest

| Metric | Backtest (2 years) | Live Dry Run (30 days) | Difference |
|--------|-------------------|----------------------|------------|
| Win Rate | 76.9% | ${WIN_RATE}% | $(echo "scale=1; $WIN_RATE - 76.9" | bc -l)% |
| Total Return | +65.6% | ${TOTAL_RETURN}% | $(echo "scale=1; $TOTAL_RETURN - 65.6" | bc -l)% |

---

## 🎯 Signal Log

MD

# Add signal log
jq -r 'select(.signal_active==true) | "- **\(.date)**: \(.consecutive_red) red days, BTC at \$\(.btc_price)"' $DAILY_DIR/*_report.json 2>/dev/null >> "$OUTPUT_FILE" || echo "No signals detected in 30 days" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << MD

---

## 📝 Trade Log

MD

# Add trade log
tail -50 "$HOME/cce/engines/four-red-days/dryrun.log" 2>/dev/null | grep -E "(ENTER|EXIT)" | tail -20 | while read line; do echo "- \`$line\`"; done >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << MD

---

## ✅ Evaluation Checklist

- [ ] Win rate within 10% of backtest (76.9%)
- [ ] Total return positive
- [ ] Max drawdown < 15%
- [ ] No unexpected behavior
- [ ] Signals generated as expected

---

## 🚀 Recommendation

MD

# Add recommendation
if (( $(echo "$WIN_RATE > 65" | bc -l 2>/dev/null) )) && (( $(echo "$TOTAL_RETURN > 0" | bc -l 2>/dev/null) )); then
    cat >> "$OUTPUT_FILE" << MD
**✅ READY FOR LIVE DEPLOYMENT**

The strategy has maintained its edge during the 30-day dry run.
Flip status to 'live' in manifest.json and deploy with \$100 capital.
MD
else
    cat >> "$OUTPUT_FILE" << MD
**⚠️ NEEDS MORE VALIDATION**

Performance is below backtest expectations. Run for another 30 days or review parameters.
MD
fi

cat >> "$OUTPUT_FILE" << MD

---

*Report generated by Kraken Intelligence — Four Red Days Evaluation System*
MD

echo ""
echo "════════════════════════════════════════════════════════════"
echo "📊 30-Day Evaluation Report Generated"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Report saved: $OUTPUT_FILE"
echo ""
echo "Quick Summary:"
echo "  Days: $TOTAL_DAYS"
echo "  Return: ${TOTAL_RETURN}%"
echo "  Win Rate: ${WIN_RATE}%"
echo "  Max Drawdown: ${MAX_DRAWDOWN}%"
